#load "paket-files/fsprojects/FSharpx.Collections/src/FSharpx.Collections/Collections.fs"
      "paket-files/fsprojects/FSharpx.Collections/src/FSharpx.Collections/LazyList.fsi"
      "paket-files/fsprojects/FSharpx.Collections/src/FSharpx.Collections/LazyList.fs"
      "paket-files/hedgehogqa/dotnet-hedgehog/Hedgehog/Numeric.fs"
      "paket-files/hedgehogqa/dotnet-hedgehog/Hedgehog/Seed.fs"
      "paket-files/hedgehogqa/dotnet-hedgehog/Hedgehog/Tree.fs"
      "paket-files/hedgehogqa/dotnet-hedgehog/Hedgehog/Random.fs"
      "paket-files/hedgehogqa/dotnet-hedgehog/Hedgehog/Shrink.fs"
      "paket-files/hedgehogqa/dotnet-hedgehog/Hedgehog/Gen.fs"
      "paket-files/hedgehogqa/dotnet-hedgehog/Hedgehog/Property.fs"
